1. Add installation BOOT.CSV file for UEFI and UEFI Secure boot fallback recovery. 2. Create EFI/BOOT directory in all cases of UEFI boot.
Signed-off-by: Michael Shych <michaelsh@nvidia.com>

diff --git a/installer/grub-arch/install-arch b/installer/grub-arch/install-arch
--- a/installer/grub-arch/install-arch
+++ b/installer/grub-arch/install-arch
@@ -765,15 +765,29 @@ install_uefi_loader()
     install_grub_config $boot_dir
 
     # Create default EFI loader BOOT/BOOTX64.efi
-    if [ "$image_secure_boot" = "yes" ] && [ "$install_firmware" = "uefi" ] ; then
-        local loader_dir="${uefi_dir}/EFI/onie"
-        local BOOT_dir="${uefi_dir}/EFI/BOOT"
-        mkdir -p $BOOT_dir
-        cp -rf $loader_dir/* ${BOOT_dir}/ || {
-            echo "ERROR: Unable to copy loader directory: $loader_dir to ${BOOT_dir}"
-            return 1
-        }
+    local loader_dir="${uefi_dir}/EFI/onie"
+    local BOOT_dir="${uefi_dir}/EFI/BOOT"
+    mkdir -p $BOOT_dir
+    cp -rf $loader_dir/* ${BOOT_dir}/ || {
+        echo "ERROR: Unable to copy loader directory: $loader_dir to ${BOOT_dir}"
+        return 1
+    }
+    if [ "$image_secure_boot" = "yes" ]; then
         mv "${BOOT_dir}/shimx64.efi" "${BOOT_dir}/BOOTX64.EFI"
+        if [ -e "$onie_root_dir/grub/BOOT.CSV_secured" ] ; then
+            mv "$onie_root_dir/grub/BOOT.CSV_secured" "${loader_dir}/BOOT.CSV"
+        fi
+        if [ -e "$onie_root_dir/grub/BOOT.CSV" ] ; then
+            rm "$onie_root_dir/grub/BOOT.CSV"
+        fi
+    else
+        mv "${BOOT_dir}/grubx64.efi" "${BOOT_dir}/BOOTX64.EFI"
+        if [ -e "$onie_root_dir/grub/BOOT.CSV" ] ; then
+            mv "$onie_root_dir/grub/BOOT.CSV" "${loader_dir}/BOOT.CSV"
+        fi
+        if [ -e "$onie_root_dir/grub/BOOT.CSV_secured" ] ; then
+            rm "$onie_root_dir/grub/BOOT.CSV_secured"
+        fi
     fi
 }
 
@@ -901,6 +915,10 @@ install_image()
             echo "Error: Problems installing GRUB on device: ${onie_boot_dev}, $onie_boot_mnt"
             exit 1
         }
+        # Clean BOOT.CSV file that is relevant just for UEFI boot
+        if ls "$onie_root_dir/grub/"BOOT.CSV* 1> /dev/null 2>&1; then
+            rm "$onie_root_dir/grub/"BOOT.CSV*
+        fi
     fi
 
     # Restore the previous grubenv file
